#include "Tone32.h"

#define BUZZER_PIN 26
#define BUZZER_CHANNEL 0

void setup() {
    tone32(BUZZER_PIN, NOTE_C4, 500, BUZZER_CHANNEL);
  noTone32(BUZZER_PIN, BUZZER_CHANNEL);
  tone32(BUZZER_PIN, NOTE_D4, 500, BUZZER_CHANNEL);
  noTone32(BUZZER_PIN, BUZZER_CHANNEL);
  tone32(BUZZER_PIN, NOTE_E4, 500, BUZZER_CHANNEL);
  noTone32(BUZZER_PIN, BUZZER_CHANNEL);
  tone32(BUZZER_PIN, NOTE_F4, 500, BUZZER_CHANNEL);
  noTone32(BUZZER_PIN, BUZZER_CHANNEL);
  tone32(BUZZER_PIN, NOTE_G4, 500, BUZZER_CHANNEL);
  noTone32(BUZZER_PIN, BUZZER_CHANNEL);
  tone32(BUZZER_PIN, NOTE_A4, 500, BUZZER_CHANNEL);
  noTone32(BUZZER_PIN, BUZZER_CHANNEL);
  tone32(BUZZER_PIN, NOTE_B4, 500, BUZZER_CHANNEL);
  noTone32(BUZZER_PIN, BUZZER_CHANNEL);

}

void loop() {
}
